# Generated by Django 4.1.1 on 2022-10-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_social_twitter"),
        ("projects", "0004_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project", options={"ordering": ["created"]},
        ),
        migrations.RenameField(
            model_name="review", old_name="projects", new_name="project",
        ),
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review", unique_together={("owner", "project")},
        ),
    ]
