# Generated by Django 4.1.1 on 2022-10-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_alter_project_options_rename_projects_review_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
